name: Build

# Controls when the workflow will run
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-go@v6
        with:
          go-version: "^1.24"

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential cmake git libsdl2-dev wget
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt-get update -qq
          sudo apt-get install -y vulkan-sdk

      - name: Build
        run: |
          make GGML_VULKAN=ON

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: dictate-linux-x86_64
          path: ./dictate

  build-mac-arm64:
    runs-on: macos-26
    env:
      MACOSX_DEPLOYMENT_TARGET: 11.0
      CGO_LDFLAGS_ALLOW: ".*"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-go@v6
        with:
          go-version: "^1.24"

      - name: Build SDL
        run: |
          wget https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.32.8.tar.gz
          tar xvfz release-2.32.8.tar.gz
          mkdir build
          cd build
          cmake ../SDL-release-2.32.8 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          sudo cmake --install .

      - name: Build
        run: |
          make GGML_VULKAN=OFF

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: dictate-macos-arm64
          path: ./dictate

  build-mac-x86_64:
    runs-on: macos-15-intel
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.15
      CGO_LDFLAGS_ALLOW: ".*"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-go@v6
        with:
          go-version: "^1.24"

      - name: Build SDL
        run: |
          wget https://github.com/libsdl-org/SDL/archive/refs/tags/release-2.32.8.tar.gz
          tar xvfz release-2.32.8.tar.gz
          mkdir build
          cd build
          cmake ../SDL-release-2.32.8 -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          sudo cmake --install .

      - name: Build
        run: |
          make GGML_VULKAN=OFF

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: dictate-macos-x86_64
          path: ./dictate

  build-windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-go@v6
        with:
          go-version: "^1.24"

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          install: >-
            base-devel
            git
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-SDL2
            mingw-w64-ucrt-x86_64-vulkan-loader
            mingw-w64-ucrt-x86_64-vulkan-headers
            mingw-w64-ucrt-x86_64-shaderc
            mingw-w64-ucrt-x86_64-spirv-headers
            mingw-w64-ucrt-x86_64-go

      - name: Build
        shell: msys2 {0}
        run: |
          make GGML_VULKAN=ON

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: dictate-windows-x86_64
          path: ./dictate.exe
